10606 – Display tooltips when hovering over geoographies
NYCPlanning/equity-tool pull request #177
Opened 2022-09-23 15:17 UTC by bmarchena

Resolves AB[#10606](https://dev.azure.com/NYCPlanning/ITD/_sprints/taskboard/Open%20Source%20Engineering/ITD/2022/Q3/Sprint%20T?workitem=10606).

This PR adds a tooltip when hovering over geographies on the map in both CD and DRM views. It adds an additional state variable to [geography].tsx which tracks the information about the currently hovered geography.

TODO:
- Currently there is an outstanding issue where the map rerenders when hovering over a geography in a view for the first time. 
- The tooltip also does not currently disappear when hovering over an invalid geography.

![Screen Shot 2022-09-23 at 11 17 08 AM](https://user-images.githubusercontent.com/43344288/191995069-4df0cae2-947f-4903-a89d-e357468ccd61.png)

2022-09-23 17:17 UTC, TylerMatteo requested changes

2022-09-23 17:17 UTC, TylerMatteo commented on src/hooks/useLayers/useLayers.ts
> +        info.layer?.props.visible ? setTooltip(info) : setTooltip({});
Are you sure you need these `props.visible` checks? I think Deck only calls onHover for visible layers by default

2022-09-23 17:17 UTC, TylerMatteo commented on src/components/Map/Map.tsx
> +            position: "absolute",
It looks like the tooltip should be centered under the cursor in the Figma. It also has the little [arrow](https://chakra-ui.com/docs/components/tooltip/usage#with-arrow) that Chakra's tooltip supports but Design might be cool with dropping that if we are having trouble using Chakra's tooltip component within the map.

2022-09-23 17:17 UTC, TylerMatteo commented on src/components/Map/Map.tsx
> +  hoverInfo: any | null;
Maybe we can replace this `any` with a proper type as well? This one might be a littler trickier.

2022-09-23 18:11 UTC, bmarchena commented on src/hooks/useLayers/useLayers.ts
> +        info.layer?.props.visible ? setTooltip(info) : setTooltip({});
good call, thought i needed them to clear the tooltip state but it's not necessary

2022-09-23 18:12 UTC, bmarchena commented on src/components/Map/Map.tsx
> +      tooltipText = hoverInfo?.object?.properties.boroname;
yup just saw the copy and updated in my last commit

2022-09-23 18:13 UTC, bmarchena commented on src/components/Map/Map.tsx
> +            position: "absolute",
gonna try using the Chakra tooltip but without a built-in component to handle that style I could see it being a non-trivial lift to get the arrow centered. digging into it

2022-09-26 14:11 UTC, bmarchena commented on src/components/Map/Map.tsx
> +            position: "absolute",
looks like the Chakra Tooltip component only really works when it's wrapping the content we want to display a tooltip over and it isn't really gonna work with our implementation of the EDDE map/layers. maybe we can punt on the arrow for now if that's ok with design?

2022-09-26 20:58 UTC, TylerMatteo commented on src/components/Map/Map.tsx
> +            position: "absolute",
Understood. I'll ask design about dropping the arrow but I doubt it will be a problem. Were you able to get the tooltip to be centered under the mouse without the arrow? I could see how that would be tricky without having Chakra's props to lean on so that might also be negotiable.

2022-09-27 15:38 UTC, bmarchena commented on src/components/Map/Map.tsx
> +            position: "absolute",
just added that in the last commit, had to use add a ref but it's working well now

2022-09-29 14:49 UTC, TylerMatteo commented
@bmarchena  this all looks good to me but I'm going to hold off on approving this until I merge in a branch I'm working on to fix the builds. You may have noticed that the GH actions that kick off when you push to your branch are failing to actually do preview deploys. Once that's in, I can help you rebase if there are any conflicts.

2022-10-11 13:50 UTC, bmarchena commented on src/hooks/usePumaInfo/usePumaInfo.ts
> +  if (id) geoid = id;
@TylerMatteo I actually ended up adding this back as an optional param if that's cool with you. The useGeoid hook will always return a null geoid on the default map page so we'll have to pass that along for each hovered geo for the tooltip to work as intended.

2022-10-11 15:34 UTC, TylerMatteo approved these changes

2022-10-11 15:34 UTC, TylerMatteo commented on src/hooks/usePumaInfo/usePumaInfo.ts
> +  if (id) geoid = id;
Ah, gotcha. Yeah this is fine. You don't _technically_ need a hook here so if we wanted to be really strict we could move some of this code to a generic "getPumaInfo" function that you could call directly and my hook would call but that's probably a bit over kill.

2022-10-11 17:21 UTC, merged