Task/10651 geo labels on map
NYCPlanning/equity-tool pull request #178
Opened 2022-09-27 13:58 UTC by dhochbaum-dcp

### Summary
As a user, I want to be able to view geography labels at relevant zoom levels so that I can more easily navigate the map, similarly to how I see labels on PFF.

For the Community Data map, this includes starting with the borough names, then the PUMA names at medium zoom levels, and adding in more specific NTA labels as I zoom in closer.

For the DRI map, this includes starting with the borough names, then the NTA labels as I zoom in closer

Acceptance Criteria:
1) at lower zoom levels, borough names display
2) at mid zoom levels, PUMA labels (names only) display
3) at higher zoom levels, NTA labels also appear in smaller font than PUMA

Figma for reference:

[https://www.figma.com/file/8ExFFiN7KDe6vzoQchnOJC/EDDE-1.1?node-id=226%3A23801](https://www.figma.com/file/8ExFFiN7KDe6vzoQchnOJC/EDDE-1.1?node-id=226:23801)

#### Tasks/Bug Numbers
 - Implements [AB#10651](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/10651)

### Technical Explanation

### Any other info you think would help a reviewer understand this PR?

2022-10-05 16:18 UTC, TylerMatteo requested changes

2022-10-05 16:18 UTC, TylerMatteo commented on src/hooks/useLayers/createCompositeLayers.ts
> +    } else if (layer.id.slice(-13) === "_ntatextlayer") {
I wouldn't hold up the PR over this but maybe give some thought to how else you could identify the layer here. Having to slice up strings to do text matching can get bug-prone over time.

2022-10-05 16:18 UTC, TylerMatteo commented on src/hooks/useLayers/useLayers.ts
> +      // id: BOROUGH,
Just a heads up to remember to clean up any leftover comments before this gets final approval.

2022-10-05 17:41 UTC, dhochbaum-dcp commented on src/hooks/useLayers/createCompositeLayers.ts
> +        {},
I can't recall why those are there - I've removed them.

2022-10-05 17:41 UTC, dhochbaum-dcp commented on src/hooks/useLayers/useLayers.ts
> +      // id: BOROUGH,
Removed.

2022-10-05 18:08 UTC, dhochbaum-dcp commented on src/hooks/useLayers/createCompositeLayers.ts
> +    } else if (layer.id.slice(-13) === "_ntatextlayer") {
These match the strings that are added in the creation of the layer above.  There really isn't anything else that exists that is unique that it makes sense to use (I could check maxWidth or something, but that is really a layer of abstraction that makes things more bug-prone).  I could add a field to each layer specifically for this, but I'm not sure that would make things any less complicated.

2022-10-17 19:11 UTC, TylerMatteo approved these changes

2022-10-17 19:13 UTC, merged