11091 initial commit
NYCPlanning/equity-tool pull request #191
Opened 2022-10-21 21:19 UTC by horatiorosa

### Summary

#### Tasks/Bug Numbers
 - Fixes AB#1234

 - Related AB#1235
 - Reverses AB#1222

### Technical Explanation

### Any other info you think would help a reviewer understand this PR?

2022-11-03 21:16 UTC, TylerMatteo commented on package.json
> -    "e2e:run": "cypress run --config video=false",
???

2022-11-07 14:28 UTC, horatiorosa commented on package.json
> -    "e2e:run": "cypress run --config video=false",
I put it back, sorry!

2022-11-09 15:49 UTC, TylerMatteo requested changes

2022-11-09 15:49 UTC, TylerMatteo commented on src/pages/api/feedback.ts
> +    if (req.method === "POST") {
This is correct for enforcing `POST` but you need an else. Just sending an error with a 404 code for any other method should be fine.

2022-11-09 15:49 UTC, TylerMatteo commented on src/schemas/feedbackSchema.ts
> +  to: Yup.string().default(""),
I think you can get rid of this, no? This schema is meant to be a representation of your form, which seems to only have 3 fields - name, email, and feedback.

2022-11-09 15:49 UTC, TylerMatteo commented on src/schemas/feedbackSchema.ts
> +  subject: Yup.string().default("EDDE Feedback"),
Same as `to`.

2022-11-09 15:49 UTC, TylerMatteo commented on src/components/ContactForm/ContactForm.tsx
> +      console.error("submit error", error);
Thoughts on how we should properly handle this error state? We'll want to at least show an error to the user and possibly also reset the form's state so that they can try again.

2022-11-09 15:49 UTC, TylerMatteo commented on src/pages/api/feedback.ts
> +type ResponseData = {
I think we can improve the variable naming and typing here. Naming is always subjective but I think "response" is a little redundant in this content. And whatever the name is, I think the single property of this type could be more specifically typed than `any`. `responseMessage` implies to me that it's just a string but I see below that you're passing in the whole response object that we get from SG.

2022-11-09 15:49 UTC, TylerMatteo commented on src/pages/api/feedback.ts
> +      res.status(res.statusCode).json({ responseMessage });
We probably don't want to return the whole response that comes back from SG. I'm assuming they're giving us back some sort of object? You might want to return just the info we need on the front end.

2022-11-09 15:49 UTC, TylerMatteo commented on src/pages/api/feedback.ts
> +    res.status(res.statusCode).json(error);
Sorta the same issue as in the try block - This is going to send back the whole response object (headers and all). A couple approaches you could take:
* You might want to return just a generic error message with only as much detail as you need on the FE
* Only return party of the error object. [SG's docs](https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/mail#quick-start-hello-email) seem to suggest there would be a `body` property at `error.response.body`

2022-11-09 22:03 UTC, horatiorosa commented on src/schemas/feedbackSchema.ts
> +  to: Yup.string().default(""),
Yea, I think we can cut the TO from this schema.

2022-11-10 15:44 UTC, horatiorosa commented on src/components/ContactForm/ContactForm.tsx
> +      console.error("submit error", error);
Got a quick mock-up from design and it's implemented.

2022-11-10 16:10 UTC, horatiorosa commented on src/pages/api/feedback.ts
> +      res.status(res.statusCode).json({ responseMessage });
Not sure how to fix this one. If I set the type as a Object, I get errors here if I try `responseMessage.body}`

2022-11-10 18:29 UTC, TylerMatteo commented on src/schemas/feedbackSchema.ts
> +  subject: Yup.string().default("EDDE Feedback"),
You can have that without have that here, no? Remember - this schema describes the actual form you're showing to the user. If there is not an input box on the screen asking the user for something called "subject", you should not have a property here. If you want to always set this string as the subject of the email, that can be done directly in the API handler.

2022-11-10 19:24 UTC, TylerMatteo commented on src/components/Contact/ContactForm.tsx
> +      console.error("submit error", error);
You can get rid of this now. Logging things in production is pretty much never a good habit to get into. At best, it's spamming users browsers, at worst, it exposes info we don't want to expose

2022-11-14 20:57 UTC, TylerMatteo commented on src/components/Contact/ContactForm.tsx
> +  const characterCount = (e: any) => {
Won't hold up merging for this but you should be able to type the `e`. It would be some sort of HTML Event object. Also, this is a little subjective but think about naming event handler functions in a way that suggests that they're handlers...like`onFeedbackChange` or something. I just think it makes things clearer because at first glance one might assume that `characterCount` is a number, not a function.

2022-11-14 20:57 UTC, TylerMatteo submitted a review, later dismissed

2022-11-14 21:30 UTC, horatiorosa commented on src/components/Contact/ContactForm.tsx
> +  const characterCount = (e: any) => {
good point. I changed the func. name to `getCharacterCount`.

2022-11-14 22:13 UTC, TylerMatteo approved these changes

2022-11-14 22:16 UTC, merged