Refactored components from functions to classes, added scroll to top
NYCPlanning/equity-tool pull request #197
Opened 2022-11-03 14:42 UTC by dhochbaum-dcp

### Summary

#### Tasks/Bug Numbers
 - Fixes AB#1234

 - Related AB#1235
 - Reverses AB#1222

### Technical Explanation

### Any other info you think would help a reviewer understand this PR?

2022-11-03 15:41 UTC, horatiorosa commented
I was wondering if you saw this possible solution for scrolling to the top on page changes:
https://github.com/vercel/next.js/discussions/15337

2022-11-03 16:14 UTC, godfreyyeung commented on src/pages/about.tsx
> +  constructor(props: any) {
Is this necessary? Would(n't) it automatically call super by default if you didn't define a constructor here?

2022-11-03 16:14 UTC, godfreyyeung commented on src/pages/methods.tsx
> +  constructor(props: any) {
same comment here

2022-11-03 18:19 UTC, dhochbaum-dcp commented on src/pages/about.tsx
> +  constructor(props: any) {
Looks like you're right, I've updated this to remove it.

2022-11-03 18:22 UTC, dhochbaum-dcp commented
> I was wondering if you saw this possible solution for scrolling to the top on page changes: [vercel/next.js#15337](https://github.com/vercel/next.js/discussions/15337)

I did not, but it appears to be a much more complicated solution, and not necessarily effective.

2022-11-03 18:53 UTC, TylerMatteo requested changes

2022-11-03 18:53 UTC, TylerMatteo commented on src/pages/about.tsx
> +class AboutPage extends React.Component {
I'm going to pull this and see if I can get it the same behavior working with `useEffect`. Reeeaalllly don't want to introduce class components if we can help it.

2022-11-07 15:22 UTC, TylerMatteo approved these changes
Lgtm. I think needing a "back to top" element just to have something to scroll is less than ideal but it's a good enough workaround for now, especially considering that this is apparently a [known issue](https://github.com/vercel/next.js/issues/28778) in Next at the moment.

2022-11-07 16:21 UTC, merged