Update data dictionary
NYCPlanning/equity-tool pull request #207
Opened 2023-02-14 19:44 UTC by TangoYankee

### Summary

**Issue context**
- Link to data dictionary is outdated
- Multiple instances of the link exist

**Proposed Fix**
- Create a constant to hold the link
  - This makes it easier to identify all the places where the link is used
  - It also makes it faster to update the link everywhere
- Replace the outdated link with the current link   

#### Tasks/Bug Numbers
 - Fixes AB#12256

### Technical Explanation
- The constants folder appeared to be the best place to hold the links
- I used an object, to allow for more external links to be added later

### Any other info you think would help a reviewer understand this PR?
- I realize this might be overkill. So, I also have a version where I just swap the old link for the new one with a 'find and replace'. I can submit that one for review, if it's preferable.

2023-02-14 21:59 UTC, TylerMatteo requested changes

2023-02-14 21:59 UTC, TylerMatteo commented on src/constants/externalLink.ts
> +export const EXTERNAL_LINK = {
Overall, I'm cool with putting this in a constant since it shows up in a couple spots.

This is very nitpicky and subjective but could you have this file just export strings? So this would become something like `export const DATA_DICTIONARY = "https://www.nyc.gov/assets/planning/download/pdf/data-maps/edde/edde-data-dictionary.pdf"`, and the import would change accordingly. Other links that are added later can just be new named exports in this same file.

2023-02-15 14:26 UTC, TangoYankee commented on src/constants/externalLink.ts
> +export const EXTERNAL_LINK = {
change is in

2023-02-15 14:47 UTC, merged

2023-02-15 14:49 UTC, horatiorosa reviewed
🚀 
this is better than a swap and replace, much easier to update in the future, if it changes again.